const BAD_REQUEST_ERROR = 400;
const NOT_FOUND_ERROR = 404;
const NTERNAL_SERVER_ERROR = 500;
const CREATED_RESPONSE = 201;

const BAD_REQUEST_MESSAGE = 'Переданы некорректные данные';
const NOT_FOUND_MESSAGE = 'Данные не найдены';
const NTERNAL_ERROR_MESSAGE = 'Произошла ошибка';

module.exports = {
  BAD_REQUEST_ERROR,
  NOT_FOUND_ERROR,
  NTERNAL_SERVER_ERROR,
  CREATED_RESPONSE,
  BAD_REQUEST_MESSAGE,
  NOT_FOUND_MESSAGE,
  NTERNAL_ERROR_MESSAGE,
};
